### PR TITLE
Add instructions on how to use multiple phantom devices

### PR DESCRIPTION
**Pull request by pazeshun**
For https://github.com/bharatm11/Geomagic_Touch_ROS_Drivers/pull/5#issuecomment-1111296201

cc @haraduka

### CODE REVIEW

**Comment by pazeshun** [comment]
@bharatm11
Do you have any plan to merge `dual-phantom-beta` branch into master?

**Comment by bharatm11** [comment]
@pazeshun, I have not been able to test the dual-phantom-beta branch myself. I will merge it into master if you or @ykawamura96 can confirm these work without any issues.

Cheers!

**Comment by pazeshun** [comment]
@bharatm11 Thank you for your response!

> I will merge it into master if you or @ykawamura96 can confirm these work without any issues.

Then, could you merge `dual-phantom-beta` branch into master?
Because I and my lab are using this branch for more than half a year:
https://github.com/jsk-ros-pkg/jsk_robot/tree/master/jsk_panda_robot#installation-for-user-pc

If you merge, I can create another PR which supports Ubuntu 18.04.
(Device drivers for Ubuntu 18.04 should be uploaded to the `Old device drivers` folder. I can give you them and request you to upload them, or create another google drive folder and add its URL to README.)

**Comment by bharatm11** [comment]
@pazeshun Merged!
Looking forward to more collaborations :)

For Ubuntu 18.04 drivers, please share the Google Drive link here and I will merge it with the original folder.

**Comment by pazeshun** [comment]
@bharatm11 

> @pazeshun Merged!
> Looking forward to more collaborations :)

Thank you! I created #11 

> For Ubuntu 18.04 drivers, please share the Google Drive link here and I will merge it with the original folder.

Could you check https://drive.google.com/drive/folders/1Y2F3joyVa-AHFTBFetRMY5ibAX4DlTnk?usp=share_link ?
Because the installation instructions on Ubuntu 18.04+ are completely different from Ubuntu 14.04, our lab decided to upload the official instruction documents as well as drivers and relay them.
cf. https://github.com/jsk-ros-pkg/jsk_robot/tree/67430717d8ce36fcccc95550f04234678221ef4d/jsk_panda_robot#installation-for-user-pc
I created #11 on the basis of that style, so it may not satisfy you.

**Comment by bharatm11** [comment]
@pazeshun have you noticed sudden intermittent losses of haptic feedback on the Geomagic touch? I remember having issues with that a couple of years ago and noticed someone at my lab saw the same problem. I'm guessing it's because of overheating. The issue resolves itself on power cycle of the device. Do you have any ideas?

**Comment by pazeshun** [comment]
@bharatm11 

> @pazeshun have you noticed sudden intermittent losses of haptic feedback on the Geomagic touch?

We have not faced that issue.
Our TouchUSBs were bought in 2021, so that issue may be resolved in later models.

**Pull request merged**
